version: '2.1'

# docker-compose build domainconnect
# docker-compose run --rm domainconnect
# docker-compose up
# docker-compose run --rm domainconnect bash

services:
 web:
   build: 
     context: .
     dockerfile: docker/Dockerfile-web
   volumes:
     - .:/workspace/
   command: "uwsgi docker/uwsgi.ini"
 
 nginx:
   image: nginx:latest
   ports:
     - "8001:80"
   volumes:
     - ./docker/exampleservice.domainconnect.local:/etc/nginx/conf.d/exampleservice.domainconnect.local.conf
   depends_on:
     - web
