FROM centos:7

# docker build -t image-name .
# docker run --rm -v `pwd`:/workspace
# docker run -v `pwd`:/workspace -it image-name
# docker run --rm -v `pwd`:/workspace -it image-name /bin/bash

#RUN pip install bottle

WORKDIR /workspace

#CMD ["python statelesshosting.py"]

yum install epel-release -y
yum install python-pip -y
yum install gcc -y
pip install bottle 
pip install dnspython 
yum install python-devel -y
pip install pycrypto
yum erase httpd http-tools apr apr-util
yum install nginx -y
yum install uwsgi -y
yum install uwsgi-plugin-python -y
pip install requests
